### PR TITLE
Update Pinocchio features

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by jslee02** [comment]
Also, according to the repository, the license of the library is still [LGPL-3.0](https://github.com/stack-of-tasks/pinocchio/blob/v2.0.0-alpha/COPYING.LESSER). Am I missing something here?

**Comment by jcarpent** [comment]
I will keep the Pinocchio website even if it is not up to date.

**Comment by jcarpent** [comment]
Concerning the license, we are changing from LGPL-3.0 to BSD-2-Clause. See stack-of-tasks/pinocchio#549 for further details.

**Comment by jcarpent** [comment]
Thanks for the merging.

**Pull request merged**
